version: '3'
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Da4EhBEQ5FiUmleVeFF1'
      MSSQL_PID: Developer
    container_name: db
    hostname: db
    ports:
      - '1433:1433'
  colour-api:
    depends_on:
      - db
    build: .
    ports:
      - '8080:80'
